// swift-tools-version:5.9
import PackageDescription

// SonarCore: Swift bindings for the Rust `sonar-core` engine (Marmot/MLS over
// Nostr + identity). Sources/SonarFFI.swift and Frameworks/sonarffi.xcframework
// are GENERATED by core/build-ios.sh — do not edit them by hand.
let package = Package(
    name: "SonarCore",
    platforms: [
        .iOS(.v16),
        .macOS(.v13),
    ],
    products: [
        .library(
            name: "SonarCore",
            targets: ["SonarCore"]
        ),
    ],
    targets: [
        // Generated UniFFI Swift bindings over the Rust static library.
        .target(
            name: "SonarCore",
            dependencies: [
                "sonarffi",
            ],
            path: "Sources",
            linkerSettings: [
                // SQLCipher (mdk-sqlite-storage → rusqlite bundled-sqlcipher) is
                // compiled against Apple CommonCrypto (-DSQLCIPHER_CRYPTO_CC), so
                // the consuming app must link these frameworks. The Rust build
                // emits `cargo:rustc-link-lib=framework=...` but static-lib
                // xcframeworks don't propagate that to Xcode — declare it here.
                .linkedFramework("Security"),
                .linkedFramework("CoreFoundation"),
                // cpal's CoreAudio backend (P2P call mic/speaker, behind the Rust
                // `calls-audio` feature) links these Apple audio frameworks. Same
                // static-lib gotcha as above — declare them for the consumer.
                // Harmless when the xcframework is built without calls-audio.
                .linkedFramework("AudioToolbox"),
                .linkedFramework("CoreAudio"),
                .linkedFramework("AVFoundation"),
                // iroh's network-interface/DNS discovery (netdev, hickory-resolver,
                // system_configuration crates) calls SystemConfiguration. Same
                // static-lib gotcha — the framework link isn't propagated.
                .linkedFramework("SystemConfiguration"),
            ]
        ),
        // Binary framework containing the Rust static library + C headers.
        .binaryTarget(
            name: "sonarffi",
            path: "Frameworks/sonarffi.xcframework"
        ),
    ]
)
