#!/usr/bin/env bash
# scripts/smoke/relay-smoke-agents.sh
#
# Hermes-native AI-agent conversation smoke test (option B).
#
# Unlike the deterministic delivery gate (relay-smoke.sh), this spins up N Sonar
# identities that hold REAL conversations: each reply is generated by an LLM via a
# configurable command (Hermes by default) and sent back over sonar-cli. It builds
# a seeded random graph, seeds opening lines, then runs ROUNDS of drain -> generate
# reply -> send, and reports message flow, reply latency and errors, plus a full
# conversation log.
#
# The orchestrator owns the loop and calls one reply command per message, so it
# does NOT need N Hermes gateways — a single `hermes chat` invocation per reply
# uses the Hermes model provider. It is fully testable WITHOUT Hermes by setting
# AGENT_REPLY_CMD to a dummy (e.g. echo), which exercises every part of the
# plumbing except the model itself.
#
# Written for bash 3.2 (macOS) and 4+ (CI): no associative arrays.
#
# Usage:
#   scripts/smoke/relay-smoke-agents.sh                              # Hermes-driven, defaults
#   AGENT_REPLY_CMD='printf ack' scripts/smoke/relay-smoke-agents.sh  # dummy, no Hermes (test plumbing)
#   IDENTITIES=3 FANOUT=1 ROUNDS=3 scripts/smoke/relay-smoke-agents.sh
#
# The reply command receives the prompt in $AGENT_PROMPT and must print the reply
# text on stdout. Default: hermes chat -q "$AGENT_PROMPT" --yolo
# Override for OpenAI/Ollama/etc., e.g.:
#   AGENT_REPLY_CMD='curl -s http://localhost:11434/api/generate -d "{\"prompt\":\"$AGENT_PROMPT\"}" | jq -r .response'
#
# See docs/RELAY-SMOKE-AGENTS.md.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCRIPT_DIR="$ROOT/scripts/smoke"

# ---- config (env overrides) ----
TARGET_RELAY="${TARGET_RELAY:-wss://nostr.relay.hedwig.sh}"
IDENTITIES="${IDENTITIES:-3}"
FANOUT="${FANOUT:-1}"                # conversation partners per identity
ROUNDS="${ROUNDS:-3}"                # conversation rounds (seed = round 0)
SEED_DELAY="${SEED_DELAY:-3}"        # secs to let relay propagate between rounds
RECEIVE_TIMEOUT_SECS="${RECEIVE_TIMEOUT_SECS:-15}"
MAX_REPLY_CHARS="${MAX_REPLY_CHARS:-300}"
# reply generator: prompt in $AGENT_PROMPT, reply text on stdout
AGENT_REPLY_CMD="${AGENT_REPLY_CMD:-hermes chat -q \"\$AGENT_PROMPT\" --yolo}"
SONAR_CLI="${SONAR_CLI:-$ROOT/core/target/release/sonar-cli}"
METRICS_JSON="${METRICS_JSON:-}"

[[ -x "$SONAR_CLI" ]] || { echo "sonar-cli not found at $SONAR_CLI." >&2; \
  echo "Build it: cargo build -p sonar-cli --release (from $ROOT/core)" >&2; exit 2; }

# ---- portable wall-clock millis ----
if [[ "$(date +%s%N 2>/dev/null)" =~ ^[0-9]{13,}$ ]]; then
  now_ms() { local t; t=$(date +%s%N); echo "${t:0:13}"; }
else
  now_ms() { python3 -c 'import time;print(int(time.time()*1000))' 2>/dev/null \
              || awk 'BEGIN{srand();print srand()*1000}'; }
fi

log() { printf '[relay-smoke-agents] %s\n' "$*" >&2; }

# ---- personas (round-robin if more identities than personas) ----
PERSONAS=(
  "a terse sysadmin who replies in short, dry sentences"
  "an enthusiastic product designer who asks one follow-up question"
  "a cautious security engineer who questions assumptions"
  "a friendly new user curious how Sonar works"
  "a skeptical beta tester who pushes back politely"
)
persona() { printf '%s' "${PERSONAS[$(( $1 % ${#PERSONAS[@]} ))]}"; }

# ---- run state ----
WORK="$(mktemp -d /tmp/relay-smoke-agents.XXXXXX)"
CONVO_LOG="$WORK/convo.log"; : > "$CONVO_LOG"
[[ -n "$METRICS_JSON" ]] || METRICS_JSON="$WORK/metrics.json"
trap 'rm -rf "$WORK"' EXIT

HOMES=(); NPUBS=()
messages_sent=0; messages_received=0; replies_generated=0; reply_errors=0; reply_empty=0
lat_sum=0; lat_max=0; lat_n=0

provision() {
  local i home npub
  for ((i = 0; i < IDENTITIES; i++)); do
    home="$WORK/agent-$i"; mkdir -p "$home"
    "$SONAR_CLI" --home "$home" --relay "$TARGET_RELAY" init >/dev/null 2>&1
    "$SONAR_CLI" --home "$home" --relay "$TARGET_RELAY" publish >/dev/null 2>&1
    npub=$("$SONAR_CLI" --home "$home" --relay "$TARGET_RELAY" identity | jq -r '.npub // empty')
    [[ -n "$npub" ]] || { log "empty npub for agent-$i"; exit 1; }
    HOMES[i]="$home"; NPUBS[i]="$npub"
  done
  log "provisioned $IDENTITIES identities on $TARGET_RELAY"
}

build_graph() {
  GRAPH="$WORK/graph.tsv"
  local seed="${SEED:-$(date +%s)}"
  awk -v n="$IDENTITIES" -v fanout="$FANOUT" -v seed="$seed" '
  BEGIN {
    srand(seed)
    for (a = 0; a < n; a++) {
      c = 0; seen = ""
      while (c < fanout && c < n - 1) {
        b = int(rand() * n)
        if (b == a) continue
        if (index(seen, ":" b ":") > 0) continue
        seen = seen ":" b ":"
        print a "\t" b
        c++
      }
    }
  }' > "$GRAPH"
  log "graph: $(wc -l < "$GRAPH" | tr -d ' ') edges (seed=$seed)"
}

npub_to_index() {
  local target="$1" i
  for ((i = 0; i < ${#NPUBS[@]}; i++)); do
    [[ "${NPUBS[i]}" == "$target" ]] && { echo "$i"; return 0; }
  done
  echo ""
}

# history file for the unordered pair {a,b}
hist_file() {
  local a="$1" b="$2" lo hi
  if (( a < b )); then lo=$a; hi=$b; else lo=$b; hi=$a; fi
  printf '%s/hist_%s_%s.txt' "$WORK" "$lo" "$hi"
}

send_msg() { # from_idx to_idx text
  "$SONAR_CLI" --home "${HOMES[$1]}" --relay "$TARGET_RELAY" \
    send --to "${NPUBS[$2]}" --text "$3" >/dev/null 2>&1
}

# drain new inbound for agent r -> json lines on stdout
drain_new() {
  "$SONAR_CLI" --home "${HOMES[$1]}" --relay "$TARGET_RELAY" \
    listen --timeout-secs "$RECEIVE_TIMEOUT_SECS" --poll-secs 2 --no-publish 2>/dev/null || true
}

# generate a reply: prompt in $AGENT_PROMPT -> reply on stdout
generate_reply() {
  AGENT_PROMPT="$1" bash -c "$AGENT_REPLY_CMD" 2>/dev/null || true
}

trim_to() { awk -v n="$MAX_REPLY_CHARS" '{print substr($0,1,n)}'; }

main() {
  local started_at ended_at seed
  started_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  seed="${SEED:-$(date +%s)}"
  log "identities=$IDENTITIES fanout=$FANOUT rounds=$ROUNDS relay=$TARGET_RELAY seed=$seed"
  provision
  build_graph

  # round 0: seed a static opening line on each edge (no LLM cost for openers)
  local a b opener
  while IFS=$'\t' read -r a b; do
    opener="Hi, agent #$a here. Quick one: do you trust this relay for private group chats?"
    if send_msg "$a" "$b" "$opener"; then
      messages_sent=$((messages_sent + 1))
      printf 'agent%s\t->\tagent%s\t%s\n' "$a" "$b" "$opener" >> "$CONVO_LOG"
      printf 'agent%s: %s\n' "$a" "$opener" >> "$(hist_file "$a" "$b")"
    fi
  done < "$GRAPH"
  log "seeded $messages_sent opening message(s)"
  sleep "$SEED_DELAY"

  # rounds 1..ROUNDS: drain everyone, reply to each new inbound
  local round r line sender content sidx hf recent prompt t0 t1 reply lat
  for ((round = 1; round <= ROUNDS; round++)); do
    log "round $round/$ROUNDS"
    for ((r = 0; r < IDENTITIES; r++)); do
      while IFS= read -r line; do
        [[ -z "$line" ]] && continue
        sender=$(printf '%s' "$line" | jq -r '.sender // empty' 2>/dev/null)
        content=$(printf '%s' "$line" | jq -r '.content // empty' 2>/dev/null)
        [[ -z "$sender" || -z "$content" ]] && continue
        messages_received=$((messages_received + 1))
        sidx=$(npub_to_index "$sender")
        [[ -z "$sidx" ]] && continue
        printf 'agent%s\t->\tagent%s\t%s\n' "$sidx" "$r" "$content" >> "$CONVO_LOG"
        printf 'agent%s: %s\n' "$sidx" "$content" >> "$(hist_file "$sidx" "$r")"

        hf="$(hist_file "$sidx" "$r")"
        recent=$(tail -n 6 "$hf" 2>/dev/null || true)
        prompt=$(printf 'You are %s. A peer just messaged you: "%s". Reply in ONE short sentence, staying in character.\nRecent exchange:\n%s' \
                 "$(persona "$r")" "$content" "$recent")
        t0=$(now_ms)
        reply=$(generate_reply "$prompt" | trim_to)
        t1=$(now_ms)
        if [[ -z "$reply" ]]; then
          reply_empty=$((reply_empty + 1))
          continue
        fi
        replies_generated=$((replies_generated + 1))
        lat=$((t1 - t0)); lat_sum=$((lat_sum + lat)); lat_n=$((lat_n + 1))
        (( lat > lat_max )) && lat_max=$lat
        printf 'agent%s: %s\n' "$r" "$reply" >> "$hf"
        printf 'agent%s\t<-\tagent%s\t%s\n' "$r" "$sidx" "$reply" >> "$CONVO_LOG"
        if send_msg "$r" "$sidx" "$reply"; then
          messages_sent=$((messages_sent + 1))
        else
          reply_errors=$((reply_errors + 1))
        fi
      done < <(drain_new "$r")
    done
    sleep "$SEED_DELAY"
  done

  ended_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  local avg_lat=0; (( lat_n > 0 )) && avg_lat=$((lat_sum / lat_n))

  jq -n \
    --arg started_at "$started_at" --arg ended_at "$ended_at" \
    --arg relay "$TARGET_RELAY" --arg reply_cmd "$AGENT_REPLY_CMD" \
    --argjson identities "$IDENTITIES" --argjson fanout "$FANOUT" \
    --argjson rounds "$ROUNDS" --argjson seed "$seed" \
    --argjson messages_sent "$messages_sent" --argjson messages_received "$messages_received" \
    --argjson replies_generated "$replies_generated" \
    --argjson reply_errors "$reply_errors" --argjson reply_empty "$reply_empty" \
    --argjson avg_lat "$avg_lat" --argjson max_lat "$lat_max" --argjson lat_n "$lat_n" \
    '{kind:"ai-agents-chat", started_at:$started_at, ended_at:$ended_at,
      config:{relay:$relay, identities:$identities, fanout:$fanout, rounds:$rounds, seed:$seed,
               reply_cmd:$reply_cmd},
      metrics:{messages_sent:$messages_sent, messages_received:$messages_received,
               replies_generated:$replies_generated, reply_errors:$reply_errors,
               reply_empty:$reply_empty,
               reply_latency_ms:{avg:$avg_lat, max:$max_lat, samples:$lat_n}}}' \
    > "$METRICS_JSON"

  cat "$METRICS_JSON"
  log "conversation log: $CONVO_LOG"
  log "sample:"; tail -n 12 "$CONVO_LOG" >&2 2>/dev/null || true
}

main "$@"
